name: deploy-to-heroku

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm ci
      - run: npm build --if-present
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "electronicmart" 
          heroku_email: "{{secrets.HEROKU_EMAIL}}"
