name: deploy-to-heroku

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./electronicsmart-app
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "electronicsmart-proj"
          heroku_email: "{{secrets.HEROKU_EMAIL}}"
          buildpack: "https://github.com/mars/create-react-app-buildpack.git"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./electronicsmart-backend
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "electronicsmart-proj" 
          heroku_email: "{{secrets.HEROKU_EMAIL}}"
